image: debian:latest

stages:
    - install
    - build

install:
    stage: install
    script:
        - apt-get -y update
        - apt-get -y upgrade
          apt-get -y install texlive-latex-extra
    environment:
        - DEBIAN_FRONTEND=noninteractive
build:
  stage: build
  script:
    - source ./scripts/build.sh
  artifacts:
    paths:
      - output
