image: ubuntu:latest

stages:
    - before_script
    - build

before_script:
    stage: before_script
  - apt update -y
  - apt install texlive-latex-extra

build:
  stage: build
  script:
    - tree .
    - source ./scripts/build.sh
  artifacts:
    paths:
      - output
