image: dxjoke/tectonic-docker

stages:
    - build

build:
  stage: build
  script:
    - mkdir output
    - tectonic --outdir output cv.tex
    - tectonic --outdir output cover_letter.tex
  artifacts:
    paths:
      - output
