image: rust:1.40

stages:
    - install_dependencies
    - build

install_dependencies:
  stage: install_dependencies
  script:
    cargo install tectonic
  cache:
    paths:
      - .cargo

build:
  stage: build
  script:
    - mkdir output
    - tectonic --outidr output cv.tex
    - tectonic --outidr output cover_letter.tex
  artifacts:
    paths:
      - output
