image: aergus/latex:latest

stages:
    - before_script
    - build

before_script:
    stage: before_script
  - apk update
  - apk add bash
  - apk add tree

build:
  stage: build
  script:
    - tree .
    - source ./scripts/build.sh
  artifacts:
    paths:
      - output
