image: aergus/latex:latest
stages:
    - build

build:
    stage: build
    script:
        - pwd
        - ls -la
        - tree .
        - ./scripts/build
    artifacts:
      paths:
        - output
