image: ubuntu:latest

stages:
    - install
    - build

install:
    stage: install
    script:
        - apt -y update
        - apt -y upgrade
        - apt install texlive-latex-extra

build:
  stage: build
  script:
    - tree .
    - source ./scripts/build.sh
  artifacts:
    paths:
      - output
