image: aergus/latex:latest
stages:
    - build

build:
    stage: build
    script:
        - apt -y update
        - apt -y upgrade
        - apt -y install tree
        - pwd
        - ls -la
        - ./scripts/build
    artifacts:
      paths:
        - output
