image: debian:latest

stages:
    - build

build:
    stage: build
    script:
        - apt-get -y update
        - apt-get -y upgrade
        - DEBIAN_FRONTEND=noninteractive apt-get -y install texlive-latex-extra tree bash
        - pwd
        - ls -la
        - tree .
        - ./scripts/build
    artifacts:
      paths:
        - output
