#!/bin/bash

main() {
    if [ "$1" == "clean" ]; then
        echo clean
        clean
    else
        compile_documents
    fi
}

compile_documents() {
    export WORKDIR=$(pwd)
    export TMPDIR=$(mktemp -d)
    echo "$TMPDIR"
    cp -r roles companies classes templates "$TMPDIR"
    cd "$TMPDIR"

    compile_references > /dev/null

    for role_file in roles/*.tex; do
        compile_resume $role_file > /dev/null
    done

    for company_dir in companies/*/; do
        company_file="companies/$company/company.tex"
        company=$(basename $company_dir)

        for job_file in companies/$company/jobs/*.tex; do
            job_dir="./output/$company/$job/cover_letter.tex"

            echo $company
            compile_cover_letter $job_file $company > /dev/null
        done
    done

    for pdf in $(find output -name "*.pdf" -type f); do
        compile_txt "$pdf"
    done

    tree .
    rm -rf "$WORKDIR/output"
    cp -r output "$WORKDIR"
    tree $WORKDIR/output
    #rm -rf $TMPDIR
}

compile_references() {
    references_dir=output/references
    mkdir -p "$references_dir"
    compile_latex "$references_dir" templates/references.tex
}

inject_file() {
    injection_file="$1"
    delim="$2"
    sed "/^.*$delim\$/a \\\\\input\{${injection_file/_/\\_}\}"
}

compile_latex() {
    outdir=$1
    in=$2
    args=$3
    pdflatex $args -interaction=nonstopmode -output-directory="$outdir" "$in"
}

compile_resume() {
    role_file="$1"
    role=$(basename "$role_file" .tex)
    resume_dir="./output/resume/$role"
    mkdir -p "$resume_dir"
    cat templates/resume.tex | inject_file "$role_file" ROLE_INJECTION > templates/resume.tmp.tex
    cp "templates/resume.tmp.tex" "$resume_dir/resume.tex"
    compile_latex "$resume_dir" templates/resume.tmp.tex -jobname=resume
}

compile_txt() {
    pdf_file="$1"
    pdftotext -layout -enc ASCII7 "$pdf_file"
}

compile_cover_letter() {
    job_file="$1"
    company="$2"

    job=$(basename "$job_file" .tex)

    job_dir="output/cover_letter/$company/$job/"
    mkdir -p "$job_dir" .tmp
    cat templates/cover_letter.tex |
        inject_file companies/$company/company.tex COMPANY_INJECTION |
        inject_file "$job_file" JOB_INJECTION > templates/cover_letter.tmp.tex

    cp templates/cover_letter.tmp.tex "$job_dir/cover_letter.tex"
    compile_latex "$job_dir" templates/cover_letter.tmp.tex -jobname=cover_letter
}

clean() {
    rm -rf output
}

main "$@"
