#!/bin/bash

main() {
    pushd ~/dox/resumes

    company_name="$1"
    job_title="$2"
    job_summary="$3"
    location="$4"
    url="$5"
    easy_apply="$6"

    company_dir=$(echo $company_name |
        sed 's/\(.\)\([A-Z]\)/\1-\2/g' |
        tr '[:upper:]' '[:lower:]')

    echo $company_name
    echo $job_title
    echo $job_summary
    echo $location
    echo $url
    echo $easy_apply

    echo $job
    mkdir -p "companies/$company_dir/jobs"
    cat templates/company.tex | replace_str COMPANYNAME $company_name > companies/$company_dir/company.tex

    cat templates/job.tex |
        replace_str JOBTITLE $job |
        replace_str JOBURL $url |
        replace_str JOB_SUMMARY $url |
        replace_str JOBURL $url |
            > "companies/$company_dir/jobs/$job.tex"

    popd
}

replace_str(){
    pattern=$1
    replace=$2

    sed "s/$pattern/$replace/" $file
}

main "$@"
