#!/bin/sh

replace_str(){
    pattern="$1"
    replace="$2"
    sed 's#'"$pattern"'#'"$replace"'#'
}

main() {
    pushd ~/dox/resumes > /dev/null
    scrape_file=scripts/scrapes/imported_jobs.csv
    if [[ ! -f "$scrape_file" ]]; then
        echo no jobs imported :\(
        popd > /dev/null
        exit
    fi


    while IFS=, read company_name job_title job_summary location url easy_apply scraped_date applied
    do

        company_dir="$(echo ${company_name} |
            sed 's/\s/_/g' |
            tr '[:upper:]' '[:lower:]')"

        job_file="$(echo ${job_title} |
            sed 's/\s/_/g' |
            tr '[:upper:]' '[:lower:]')"

        mkdir -p "companies/$company_dir/jobs"
        cat templates/company.tex |
            replace_str COMPANYNAME "$company_name" |
            replace_str ADDRESS "$location" > companies/$company_dir/company.tex

        cat templates/job.tex |
            replace_str SCRAPED_DATE "$scraped_date" |
            replace_str DID_APPLY "$applied" |
            replace_str JOBTITLE "$job_title" |
            replace_str JOBURL "$url" |
            replace_str JOB_SUMMARY "$job_summary" |
            replace_str EASYAPPLY "$easy_apply" > companies/$company_dir/jobs/$job_file.tex

    done < "$scrape_file"
    popd > /dev/null
}

main "$@"
