#!/bin/bash

pushd ~/dox/resumes > /dev/null

./scripts/sort_jobs

file=./easy_apply_jobs

if [[ ! -f "$file" ]]; then
    echo no imported jobs
    popd > /dev/null
    exit
fi

while IFS="," read -r line
do
    declare -A easy_apply_jobs

    echo $line
    job_file=$(echo $line | cut -d' ' -f1)
    url=$(echo $line | cut -d' ' -f2)

    echo $job_file
    echo $url
    easy_apply_jobs["$job_file"]="$url"

        #for k in "${!easy_apply_jobs[@]\n}"
        #do
        #    echo "$k" | dmenu -l 10
        #done
done <"$file"
menu=$(printf "\n%s" "${!easy_apply_jobs[@]}")
url=${easy_apply_jobs[$(echo "$menu" | rofi -selected-row 1 -dmenu -i -l 20)]}
if [ -n "$url" ]; then
    echo "$url" | xargs firefox
    chosen=$(grep $url $file | cut -f1)
    echo You chose $chosen
    sed '/Applied?: false/c\Applied?: true' -i $chosen
fi
popd > /dev/null
