#!/bin/bash
pushd ~/dox/resumes/scripts > /dev/null
SCRAPE_DIR=./scrapes

CONFIG_FILE=config.json

for i in "$SCRAPE_DIR/*"; do
    echo company_name job_title job_summary location url easy_apply

    cmd=".[] |
        (.company | gsub(\"(,|\/)\"; \" \")), \",\",
        (.title | gsub(\"(,|\/)\"; \" \")), \",\",
        (.summary | gsub(\"(,\/)\"; \" \")), \",\",
        (.location | gsub(\"(,\/)\"; \" \")), \",\",
        (.url | gsub(\"(,)\"; \" \")), \",\",
        .isEasyApply, \"\t\"
        "

    cat $i | jq -j "${cmd}" |tr '\n' ' ' | tr '\t' '\n'
done
popd > /dev/null

#         map([.]) |
#. - [\"Amazon\"] |
#. - [\"Apple\"] |
#. - [\"Facebook\"] |
#. - [\"Google\"] |
#. - [\"Ubisoft\"] |
#map(.[]) |
#| map(select(contains($companyIgnore)==false)) | map(.[]) | sort | unique"
#companyIgnore=$(cat $CONFIG_FILE | jq -rc '.companyIgnore' | sed 's/"/\\"/g')
