#!/bin/bash
pushd ~/dox/resumes/scripts > /dev/null
SCRAPE_DIR=./scrapes

CONFIG_FILE=config.json

for i in "$SCRAPE_DIR/*"; do
    cmd=".[] |
        (.company   | gsub(\"(,|\/|#)\"; \" \")), \",\",
        (.title     | gsub(\"(,|\/|#)\"; \" \")), \",\",
        (.summary   | gsub(\"(,|\/|#)\"; \" \")), \",\",
        (.location  | gsub(\"(,|\/|#)\"; \" \")), \",\",
        (.url       | gsub(\",\"; \"\\\\,\")), \",\",
        .isEasyApply, \"\t\"
        "

    cat $i | jq -j "${cmd}" |tr '\n' ' ' | tr '\t' '\n' > "$SCRAPE_DIR/imported_jobs.csv"
done
popd > /dev/null
